name: parlour_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  stylish_bottom_bar: ^1.1.1
  dotted_line: ^3.2.3
  google_fonts: ^6.3.0
  intl: ^0.20.2
  image_picker_macos: ^0.2.2
  image_picker: ^1.2.0
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  reels: ^1.0.0
  video_player: ^2.8.2
  app_settings: ^6.1.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  path_provider: ^2.1.5
  responsive_framework: ^1.5.1
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/profile/
    - assets/home/
    - assets/services/
    - assets/parlour/

